# HACK AI / Intro to Large Language Modelling
## Check for keywords in scraped web text and extract text context window

### *Mariam Cook*

### *m.cook6@exeter.ac.uk*

### *University of Exeter Centre for Computational Social Science*

In [ ]:
import pandas as pd

# Check for keywords

In [ ]:
keywordlisttocheck = ['Best Start in Life','Sure Start','family hubs', 'free school meals', 'School meals', 'Development checks',
                      'School readiness', 'breakfast clubs', 'free breakfast', 'childcare hours', 'free childcare hours',
                      'free childcare for working parents', 'tax-free childcare', 'tax free childcare', 'universal credit childcare']

In [ ]:
import re

def find_keywords_present(texttocheck, keywordlisttocheck):
  total_len = len(texttocheck)
  keywords_in_text = []
  full_results = []

  if(type(texttocheck) == str):
    texttocheck_lower = texttocheck.lower()

    for a_keyword in keywordlisttocheck:
      a_keyword_lower = a_keyword.lower()

      # Find all occurrences of the keyword
      start_pos = 0
      mention_count = 0

      while True:
        index = texttocheck_lower.find(a_keyword_lower, start_pos)

        if index == -1:  # No more occurrences found
          break

        mention_count += 1
        print(f'found this here (mention #{mention_count}): {a_keyword} at position {index}')

        keywords_in_text.append(a_keyword)

        # Calculate context window
        if index < 256:
          start_index = 0
        else:
          start_index = index - 256

        if index + 256 < total_len:
          to_end = 256
        else:
          to_end = total_len - index

        full_result = (a_keyword, mention_count, texttocheck_lower[start_index:index + to_end])
        if len(full_result[2]) > 0:
          full_results.append(full_result)

        # Move search position past this occurrence
        start_pos = index + len(a_keyword_lower)

  return full_results

In [ ]:
find_keywords_present('my example ---- test my result is Sure Start and here is some more text test some more and here is a giraffe test\
 my result is Sure Start and here is some more text test some more and here is a giraffe',
                      keywordlisttocheck)

found this here (mention #1): Sure Start at position 34
found this here (mention #2): Sure Start at position 127

[('Sure Start',
  1,
  'my example ---- test my result is sure start and here is some more text test some more and here is a giraffe test my result is sure start and here is some more text test some more and here is a giraffe'),
 ('Sure Start',
  2,
  'my example ---- test my result is sure start and here is some more text test some more and here is a giraffe test my result is sure start and here is some more text test some more and here is a giraffe')]

In [ ]:
find_keywords_present('my result is Sure Start', keywordlisttocheck)

found this here (mention #1): Sure Start at position 13

[('Sure Start', 1, 'my result is sure start')]

# Load News data

Data credit:

*   This data is the result of querying the 2024-25 common crawl UK government subset provided at the 2025 Bristol Datathon. [See here for the full data set (very large).](https://github.com/eshasadia/G5-CommonCrawl/blob/main/news_filtered_2024_p1_1.csv)
*   The data was further restricted to news only by [Meng Lee in our team: Group 5](https://github.com/eshasadia/G5-CommonCrawl/blob/main/data/filtered_2024_p1.csv).

In [ ]:
news_results_df = pd.DataFrame(columns=['source', 'id', 'url', 'parent_url', 'cc_url', 'content_truncated',
                                                 'result', 'mention_number', 'result_text'])
news_results_df

Empty DataFrame
Columns: [source, id, url, parent_url, cc_url, content_truncated, result, mention_number, result_text]
Index: []

In [ ]:
df_news_filtered_2024_p1 = pd.read_csv('/content/news_filtered_2024_p1.csv')

df_news_filtered_2024_p1

,url,parent_url,postcodes,cc_url,content
0,https://www.gov.uk/government/news/nato-claims...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,nato claims 'successful year' in afghanistan -...
1,https://www.gov.uk/government/news/new-british...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,new british ambassador to afghanistan visits n...
2,https://www.gov.uk/government/news/corporal-st...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,corporal stephen paul curley killed in afghani...
3,https://www.gov.uk/government/news/127-2012-1-...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,127/2012 - £1.3 million for communities gettin...
4,https://www.gov.uk/government/news/commercial-...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,commercial partner announced to help improve m...
...,...,...,...,...,...
1886,https://www.gov.uk/government/news/nick-clegg-...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,nick clegg sets out plans to end child detenti...
1887,https://www.gov.uk/government/news/praise-for-...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,praise for local community in nottingham - gov...
1888,https://www.gov.uk/government/news/hundreds-of...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,hundreds of new zero emission buses to connect...
1889,https://www.gov.uk/government/news/deputy-prim...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,deputy prime minister launches more 'city deal...
1890,https://www.gov.uk/government/news/government-...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,government launches new drive to support rural...

In [ ]:
number_results = 0
for id, row in df_news_filtered_2024_p1.iterrows():
  result = find_keywords_present(row['content'], keywordlisttocheck)

  if len(result) > 0:
    for item in result:
      number_results += 1
      data_row = {}
      print(item)

      data_row['source'] = 'df_selected_urls_2024_p1'
      data_row['id'] = id
      data_row['url'] = row['url']
      data_row['parent_url'] = row['parent_url']
      data_row['content_truncated'] = row['content'][0:100]
      data_row['cc_url'] = row['cc_url']
      data_row['result'] = item[0]  # keyword
      data_row['mention_number'] = item[1]  # mention count
      data_row['result_text'] = item[2]  # context text

      news_results_df = pd.concat([news_results_df, pd.DataFrame([data_row])], ignore_index=True)

print('number_results', number_results)

found this here (mention #1): Sure Start at position 5238
('Sure Start', 1, ' we are recruiting 4,200 health visitors and expanding programmes such as family nurse partnerships. through establishing the £2bn a year early intervention grant, we have signalled the importance of this agenda. we have committed to maintain a network of sure start children’s centres and to expand the free offer of childcare to disadvantaged two year olds, and put in place measures like the pupil premium. we are encouraging system reform through community budgets and payment by results. this package will e')
found this here (mention #1): free school meals at position 8086
found this here (mention #2): free school meals at position 8160
found this here (mention #1): School meals at position 8091
found this here (mention #2): School meals at position 8165
('free school meals', 1, 'e right for local children. international evidence shows that giving teachers and heads more freedom in the classroom helps to raise standards in education.\nfree schools and academies can also prioritise the most disadvantaged children (those eligible for free school meals) in their school admissions. with children eligible for free school meals attracting additional funding through the coalition’s pupil premium - worth £488 per pupil this year - there will be even more incentive for these schools to attrac')
('free school meals', 2, 'ers and heads more freedom in the classroom helps to raise standards in education.\nfree schools and academies can also prioritise the most disadvantaged children (those eligible for free school meals) in their school admissions. with children eligible for free school meals attracting additional funding through the coalition’s pupil premium - worth £488 per pupil this year - there will be even more incentive for these schools to attract those pupils most in need of the high-quality education they will offer.')
('School meals', 1, 'ht for local children. international evidence shows that giving teachers and heads more freedom in the classroom helps to raise standards in education.\nfree schools and academies can also prioritise the most disadvantaged children (those eligible for free school meals) in their school admissions. with children eligible for free school meals attracting additional funding through the coalition’s pupil premium - worth £488 per pupil this year - there will be even more incentive for these schools to attract tho')
('School meals', 2, 'nd heads more freedom in the classroom helps to raise standards in education.\nfree schools and academies can also prioritise the most disadvantaged children (those eligible for free school meals) in their school admissions. with children eligible for free school meals attracting additional funding through the coalition’s pupil premium - worth £488 per pupil this year - there will be even more incentive for these schools to attract those pupils most in need of the high-quality education they will offer.\nthe ')
found this here (mention #1): Best Start in Life at position 4532
('Best Start in Life', 1, ' videos showing midwives demonstrating practical advice such as bathing your baby and parents discussing issues that affected them and how they supported each other.\nsecretary of state for health, andrew lansley said:\n”we all want to give our children the best start in life. but sometimes, particularly for first-time parents, bringing a new baby home can be a daunting as well as a happy experience.\n”that is why we are determined to help people become more confident in becoming a parent - from pregnancy to t')
found this here (mention #1): Best Start in Life at position 5271
('Best Start in Life', 1, 'ure, and turned that school around. now he’s going to help us drive the nationwide transformation of our schools.\nbe in no doubt: this is a government that is incredibly ambitious for all the children in our country - and we will fight for them to get the best start in life.\nsign up to receive the prime minister’s newsletter .\nshare this page\nthe following links open in a new tab\nshare on facebook (opens in new tab)\nshare on twitter (opens in new tab)\npublished 17 january 2012\nis this page useful?\nmaybe\nyes')
found this here (mention #1): Sure Start at position 5380
('Sure Start', 1, ' back of the quango state.\nthe detailed spending decisions outlined today show a clear determination to make the necessary savings whilst minimising the impact on essential frontline services like rubbish collections and protecting spending on schools and sure start. we have focused attention on reducing the centre and it is here that the reductions are the hardest.\nsteps have been taken to limit the impact on local authorities and make savings proportionally. councils have been given the flexibility they n')
found this here (mention #1): tax-free childcare at position 0
found this here (mention #2): tax-free childcare at position 1786
found this here (mention #3): tax-free childcare at position 1869
found this here (mention #4): tax-free childcare at position 2079
found this here (mention #5): tax-free childcare at position 2407
found this here (mention #6): tax-free childcare at position 2653
found this here (mention #7): tax-free childcare at position 3973
found this here (mention #8): tax-free childcare at position 4042
found this here (mention #9): tax-free childcare at position 4191
found this here (mention #10): tax-free childcare at position 4400
found this here (mention #11): tax-free childcare at position 4944
found this here (mention #12): tax-free childcare at position 5231
found this here (mention #13): tax-free childcare at position 5403
found this here (mention #14): tax-free childcare at position 6967
found this here (mention #15): tax-free childcare at position 7032
found this here (mention #16): tax-free childcare at position 7336
found this here (mention #17): tax-free childcare at position 7386
('tax-free childcare', 1, 'tax-free childcare: 10 things parents should know - gov.uk\ncookies on gov.uk\nwe use some essential cookies to make this website work.\nwe’d like to set additional cookies to understand how you use gov.uk, remember your settings and improve government servic')
('tax-free childcare', 2, "et support with the cost of living\nfind out about the energy bills support scheme\nfind a job\nuniversal credit account: sign in\ncheck your national insurance record\ncheck mot history of a vehicle\nhome\nparenting, childcare and children's services\nnews story\ntax-free childcare: 10 things parents should know\nten things to know about the new tax-free childcare scheme.\nfrom:\nhm treasury, department for education, hm revenue & customs, and prime minister's office, 10 downing street\npublished\n18 march 2014\nlast upd")
('tax-free childcare', 3, "ind a job\nuniversal credit account: sign in\ncheck your national insurance record\ncheck mot history of a vehicle\nhome\nparenting, childcare and children's services\nnews story\ntax-free childcare: 10 things parents should know\nten things to know about the new tax-free childcare scheme.\nfrom:\nhm treasury, department for education, hm revenue & customs, and prime minister's office, 10 downing street\npublished\n18 march 2014\nlast updated\n18 march 2016 — see all updates\ntax-free childcare will be available to around")
('tax-free childcare', 4, " should know\nten things to know about the new tax-free childcare scheme.\nfrom:\nhm treasury, department for education, hm revenue & customs, and prime minister's office, 10 downing street\npublished\n18 march 2014\nlast updated\n18 march 2016 — see all updates\ntax-free childcare will be available to around 2 million households to help with the cost of childcare, enabling more parents to go out to work, if they want to, to provide greater security for their families.\nto find out about all the government’s childca")
('tax-free childcare', 5, 'elp with the cost of childcare, enabling more parents to go out to work, if they want to, to provide greater security for their families.\nto find out about all the government’s childcare offers visit the childcare choices website.\nten things to know about tax-free childcare:\n1. you’ll be able to open an online account\nyou’ll be able to open an online account, which you can pay into to cover the cost of childcare with a registered provider. this will be done through the government website, gov.uk.\ntax-free c')
('tax-free childcare', 6, 'now about tax-free childcare:\n1. you’ll be able to open an online account\nyou’ll be able to open an online account, which you can pay into to cover the cost of childcare with a registered provider. this will be done through the government website, gov.uk.\ntax-free childcare will be introduced on 21 april 2017, and will then be gradually rolled out over 2017, with parents of children aged under four (on 31 august), and parents of disabled children aged under 17 able to enter the scheme first.\nyou’ll be able ')
('tax-free childcare', 7, 'earning at least £120 a week and not more than £100,000 each per year\nthe scheme is designed to be flexible for parents if, for example, they want to get back to work after the birth of a child or work part-time.\n5. any eligible working family can use the tax-free childcare scheme - it doesn’t rely on employers offering it\ntax-free childcare doesn’t rely on employers offering the scheme, unlike the current scheme employer-supported childcare. any working family can use tax-free childcare, provided they meet')
('tax-free childcare', 8, '\nthe scheme is designed to be flexible for parents if, for example, they want to get back to work after the birth of a child or work part-time.\n5. any eligible working family can use the tax-free childcare scheme - it doesn’t rely on employers offering it\ntax-free childcare doesn’t rely on employers offering the scheme, unlike the current scheme employer-supported childcare. any working family can use tax-free childcare, provided they meet the eligibility requirements.\n6. the scheme will be available for pa')
('tax-free childcare', 9, 'y eligible working family can use the tax-free childcare scheme - it doesn’t rely on employers offering it\ntax-free childcare doesn’t rely on employers offering the scheme, unlike the current scheme employer-supported childcare. any working family can use tax-free childcare, provided they meet the eligibility requirements.\n6. the scheme will be available for parents who are self-employed\nself-employed parents will be able to get support with childcare costs in tax-free childcare, unlike the current scheme (')
('tax-free childcare', 10, 'upported childcare. any working family can use tax-free childcare, provided they meet the eligibility requirements.\n6. the scheme will be available for parents who are self-employed\nself-employed parents will be able to get support with childcare costs in tax-free childcare, unlike the current scheme (employer-supported childcare) which is not available to self-employed parents. to support newly self-employed parents, the government is introducing a ‘start-up’ period. during this, self-employed parents won’')
('tax-free childcare', 11, 'e level.\nthe scheme will be available to parents on paid sick leave and paid and unpaid statutory maternity, paternity and adoption leave.\n7. if you currently receive employer-supported childcare then you can continue to do so\nyou do not have to switch to tax-free childcare if you do not wish to. employer-supported childcare will continue to run. the current scheme will remain open to new entrants until april 2018. parents already registered by this date will be able to continue using it for as long as thei')
('tax-free childcare', 12, 't wish to. employer-supported childcare will continue to run. the current scheme will remain open to new entrants until april 2018. parents already registered by this date will be able to continue using it for as long as their employer offers it.\nhowever, tax-free childcare will be open to more than twice as many parents as employer-supported childcare.\nemployers’ workplace nurseries won’t be affected by the introduction of tax-free childcare.\n8. parents and others can pay money into their childcare account')
('tax-free childcare', 13, 'will be able to continue using it for as long as their employer offers it.\nhowever, tax-free childcare will be open to more than twice as many parents as employer-supported childcare.\nemployers’ workplace nurseries won’t be affected by the introduction of tax-free childcare.\n8. parents and others can pay money into their childcare account as and when they like\nthis gives you the flexibility to pay in more in some months, and less at other times. this means you can build up a balance in your account to use a')
('tax-free childcare', 14, 'hange to who is eligible - parents of the youngest children will now be able to apply first\n27 november 2015\nupdated to reflect that parents in work need to earn over £100 a week and not more than £100,000 per year\n3 july 2015\nupdated to reflect confirmed tax-free childcare launch.\n24 march 2014\nupdated to reflect that tax-free childcare will also be available for children with disabilities up to the age of 17.\n18 march 2014\nfirst published.\nrelated content\nwraparound and holiday childcare: responding to re')
('tax-free childcare', 15, 'now be able to apply first\n27 november 2015\nupdated to reflect that parents in work need to earn over £100 a week and not more than £100,000 per year\n3 july 2015\nupdated to reflect confirmed tax-free childcare launch.\n24 march 2014\nupdated to reflect that tax-free childcare will also be available for children with disabilities up to the age of 17.\n18 march 2014\nfirst published.\nrelated content\nwraparound and holiday childcare: responding to requests\nchildcare for service children\n30 hours free childcare: el')
('tax-free childcare', 16, "ildren with disabilities up to the age of 17.\n18 march 2014\nfirst published.\nrelated content\nwraparound and holiday childcare: responding to requests\nchildcare for service children\n30 hours free childcare: eligibility codes issued and validated\nsign up to tax-free childcare if you’re a childcare provider\ntax-free childcare\nexplore the topic\nparenting, childcare and children's services\npersonal tax reform\nuk economy\nis this page useful?\nmaybe\nyes this page is useful\nno this page is not useful\nthank you for y")
('tax-free childcare', 17, "arch 2014\nfirst published.\nrelated content\nwraparound and holiday childcare: responding to requests\nchildcare for service children\n30 hours free childcare: eligibility codes issued and validated\nsign up to tax-free childcare if you’re a childcare provider\ntax-free childcare\nexplore the topic\nparenting, childcare and children's services\npersonal tax reform\nuk economy\nis this page useful?\nmaybe\nyes this page is useful\nno this page is not useful\nthank you for your feedback\nreport a problem with this page\nhelp ")
found this here (mention #1): Sure Start at position 4479
('Sure Start', 1, '009-10.\nsocial fund: the current scheme\nthe social fund currently consists of a discretionary and a regulated scheme.\ndiscretionary scheme: community care grants, budgeting loans and crisis loans.\nregulated scheme: cold weather payments, funeral payments, sure start maternity grants and winter fuel payments.\nsocial fund: reform\nwe have already announced as part of wider welfare reform that the discretionary elements will be reformed from 2013.\nthe welfare reform white paper announced that local authorities ')
found this here (mention #1): free school meals at position 4117
found this here (mention #1): School meals at position 4122
('free school meals', 1, 'ar. of children involved in the riots and brought before the courts, two thirds had special educational needs and on average missed almost one day of school a week. they were also more likely to live in the 10 per cent lowest income areas, to be receiving free school meals and to have been excluded from school at least once.\ncharlie taylor said:\nwe currently have a flawed system that fails to provide suitable education and proper accountability for some of the most vulnerable children in the country. if we ')
('School meals', 1, 'f children involved in the riots and brought before the courts, two thirds had special educational needs and on average missed almost one day of school a week. they were also more likely to live in the 10 per cent lowest income areas, to be receiving free school meals and to have been excluded from school at least once.\ncharlie taylor said:\nwe currently have a flawed system that fails to provide suitable education and proper accountability for some of the most vulnerable children in the country. if we fail ')
found this here (mention #1): free school meals at position 2406
found this here (mention #2): free school meals at position 2732
found this here (mention #3): free school meals at position 4514
found this here (mention #1): School meals at position 2411
found this here (mention #2): School meals at position 2737
found this here (mention #3): School meals at position 4519
('free school meals', 1, 'at coalition government\nengland’s most disadvantaged pupils are set to benefit from an extra £58 each after the department for education announced this year’s pupil premium will increase to £488.\nschools receive the extra cash for every child eligible for free school meals (fsms). the money has been released because fewer-than-expected children have registered for fsms this year.\nchildren’s minister sarah teather said:\nthe pupil premium will benefit poorer pupils, providing extra money directly for those pu')
('free school meals', 2, 'an-expected children have registered for fsms this year.\nchildren’s minister sarah teather said:\nthe pupil premium will benefit poorer pupils, providing extra money directly for those pupils who need it the most.\nwe know that just 27 per cent of pupils on free school meals get 5 good gcse grades compared with 54 per cent of non-free school meal pupils. this extra funding will help tackle this inequality and enable schools to provide the extra support they need to reach their full potential.\nnews of the extr')
('free school meals', 3, 'gh the scheme.\nnotes for editors\nthe national, regional, local authority and school level allocations of the pupil premium for 2011 to 2012 can be found on our website.\nthe pupil premium for 2011 to 2012 is allocated to all pupils known to be eligible for free school meals in january 2011. the number of pupils registering in january 2011, although higher than in january 2010, was not as high as predicted when the level of the per pupil premium was announced last december. therefore, not all funding availabl')
('School meals', 1, 'alition government\nengland’s most disadvantaged pupils are set to benefit from an extra £58 each after the department for education announced this year’s pupil premium will increase to £488.\nschools receive the extra cash for every child eligible for free school meals (fsms). the money has been released because fewer-than-expected children have registered for fsms this year.\nchildren’s minister sarah teather said:\nthe pupil premium will benefit poorer pupils, providing extra money directly for those pupils ')
('School meals', 2, 'pected children have registered for fsms this year.\nchildren’s minister sarah teather said:\nthe pupil premium will benefit poorer pupils, providing extra money directly for those pupils who need it the most.\nwe know that just 27 per cent of pupils on free school meals get 5 good gcse grades compared with 54 per cent of non-free school meal pupils. this extra funding will help tackle this inequality and enable schools to provide the extra support they need to reach their full potential.\nnews of the extra cas')

In [ ]:
news_results_df

,source,id,url,parent_url,cc_url,content_truncated,result,mention_number,result_text
0,df_selected_urls_2024_p1,80,https://www.gov.uk/government/news/graham-alle...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,graham allen launches second report on early i...,Sure Start,1,"we are recruiting 4,200 health visitors and e..."
1,df_selected_urls_2024_p1,261,https://www.gov.uk/government/news/first-speci...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,first special and alternative provision free s...,free school meals,1,e right for local children. international evid...
2,df_selected_urls_2024_p1,261,https://www.gov.uk/government/news/first-speci...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,first special and alternative provision free s...,free school meals,2,ers and heads more freedom in the classroom he...
3,df_selected_urls_2024_p1,261,https://www.gov.uk/government/news/first-speci...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,first special and alternative provision free s...,School meals,1,ht for local children. international evidence ...
4,df_selected_urls_2024_p1,261,https://www.gov.uk/government/news/first-speci...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,first special and alternative provision free s...,School meals,2,nd heads more freedom in the classroom helps t...
...,...,...,...,...,...,...,...,...,...
77,df_selected_urls_2024_p1,1876,https://www.gov.uk/government/news/more-help-w...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,more help with childcare costs for working fam...,tax-free childcare,1,minister's office and the rt hon nick clegg\n...
78,df_selected_urls_2024_p1,1876,https://www.gov.uk/government/news/more-help-w...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,more help with childcare costs for working fam...,tax-free childcare,2,r nick clegg said:\ni want to help every famil...
79,df_selected_urls_2024_p1,1876,https://www.gov.uk/government/news/more-help-w...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,more help with childcare costs for working fam...,tax-free childcare,3,antly worrying about how to juggle their famil...
80,df_selected_urls_2024_p1,1884,https://www.gov.uk/government/news/pupils-who-...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,pupils who fall behind in english and maths to...,free school meals,1,ce shows that pupils who are behind in english...
81,df_selected_urls_2024_p1,1884,https://www.gov.uk/government/news/pupils-who-...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,pupils who fall behind in english and maths to...,School meals,1,ows that pupils who are behind in english and ...

In [ ]:
df_news_filtered_2024_p2 = pd.read_csv('/content/news_filtered_2024_p2.csv')

df_news_filtered_2024_p2

,url,parent_url,postcodes,cc_url,content
0,https://www.gov.uk/government/news/new-virtual...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,new virtual cyber school gives teens chance to...
1,https://www.gov.uk/government/news/blueprint-f...,www.gov.uk,['SW1P 4DF'],https://data.commoncrawl.org/crawl-data/CC-MAI...,blueprint for 100 multi-million pound town dea...
2,https://www.gov.uk/government/news/opening-doo...,www.gov.uk,['SW1H 9EX'],https://data.commoncrawl.org/crawl-data/CC-MAI...,opening doors for young disabled people to eng...
3,https://www.gov.uk/government/news/workplace-d...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,workplace dispute reforms proposed by governme...
4,https://www.gov.uk/government/news/home-secret...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,home secretary hails security agreement with e...
...,...,...,...,...,...
977,https://www.gov.uk/government/news/funding-for...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,funding for two patient safety research centre...
978,https://www.gov.uk/government/news/new-divorce...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,new divorce law to end the blame game - gov.uk...
979,https://www.gov.uk/government/news/second-pubs...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,second pubs code declaration ends today - gov....
980,https://www.gov.uk/government/news/meeting-of-...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,meeting of the withdrawal agreement joint comm...
981,https://www.gov.uk/government/news/hundreds-of...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,hundreds of new zero emission buses to connect...

In [ ]:
number_results = 0
for id, row in df_news_filtered_2024_p2.iterrows():
  result = find_keywords_present(row['content'], keywordlisttocheck)

  if len(result) > 0:
    for item in result:
      number_results += 1
      data_row = {}
      print(item)

      data_row['source'] = 'df_selected_urls_2024_p2'
      data_row['id'] = id
      data_row['url'] = row['url']
      data_row['parent_url'] = row['parent_url']
      data_row['cc_url'] = row['cc_url']
      data_row['content_truncated'] = row['content'][0:100]
      data_row['result'] = item[0]  # keyword
      data_row['mention_number'] = item[1]  # mention count
      data_row['result_text'] = item[2]  # context text

      news_results_df = pd.concat([news_results_df, pd.DataFrame([data_row])], ignore_index=True)

print('number_results', number_results)

found this here (mention #1): family hubs at position 5015
found this here (mention #1): childcare hours at position 4827
found this here (mention #1): free childcare hours at position 4822
('family hubs', 1, 'o be paid to early years providers to deliver the government’s free childcare hours.\nnew investment of £302 million to fund new programmes to support parents, provide bespoke breast feeding services and parent-infant mental support, and funding to rollout family hubs across england.\n£639 million resource funding per annum by 2024-25 as part of the government’s commitment to end rough sleeping in england, an 85% cash increase compared to 2019-20. this brings total funding to £1.9 billion resource and £109 mi')
('childcare hours', 1, 'april. alcohol duties will be frozen across the board for the third year running saving consumers £3 billion.\nadditional investment of £170 million in 2024-25 to increase the hourly rate to be paid to early years providers to deliver the government’s free childcare hours.\nnew investment of £302 million to fund new programmes to support parents, provide bespoke breast feeding services and parent-infant mental support, and funding to rollout family hubs across england.\n£639 million resource funding per annum ')
('free childcare hours', 1, 'next april. alcohol duties will be frozen across the board for the third year running saving consumers £3 billion.\nadditional investment of £170 million in 2024-25 to increase the hourly rate to be paid to early years providers to deliver the government’s free childcare hours.\nnew investment of £302 million to fund new programmes to support parents, provide bespoke breast feeding services and parent-infant mental support, and funding to rollout family hubs across england.\n£639 million resource funding per a')
found this here (mention #1): free school meals at position 2326
found this here (mention #2): free school meals at position 2982
found this here (mention #3): free school meals at position 3083
found this here (mention #4): free school meals at position 5679
found this here (mention #1): School meals at position 2331
found this here (mention #2): School meals at position 2987
found this here (mention #3): School meals at position 3088
found this here (mention #4): School meals at position 5684
('free school meals', 1, 'nment\nengland’s most disadvantaged pupils are to benefit from extra cash next year when the pupil premium rises to £900 per pupil - around 50% higher than last year.\nschools receive extra cash through the premium for every child registered as eligible for free school meals (fsm) at any point in the past six years and children in care who have been looked after for six months.\nschools minister david laws said:\nit’s unacceptable that children from disadvantaged backgrounds are less likely to do well in school')
('free school meals', 2, 'dy telling us that the pupil premium is making a difference.\nthis extra funding will help schools provide the extra support children and young people need to reach their full potential.\nstatistics show that, in 2011, the latest available:\n35% of pupils on free school meals achieved five good gcse grades compared with 62% of other pupils.\n58% of pupils on free school meals achieved the expected level in both english and maths by the end of primary school compared with 78% of other pupils.\nthe pupil premium w')
('free school meals', 3, 'vide the extra support children and young people need to reach their full potential.\nstatistics show that, in 2011, the latest available:\n35% of pupils on free school meals achieved five good gcse grades compared with 62% of other pupils.\n58% of pupils on free school meals achieved the expected level in both english and maths by the end of primary school compared with 78% of other pupils.\nthe pupil premium was introduced in april 2011 and over 1.8 million disadvantaged children are benefiting from the extra')
('free school meals', 4, 'tes to editors\nthe department for education has also confirmed that the per pupil level of the pupil premium for the financial year 2012 to 2013 will rise from £600 to £619. this follows a smaller-than-expected rise in the number of pupils registering for free school meals in january 2012. the allocations to schools will be revised to reflect this change in the per pupil amount.\ndetails of how secondary schools can sign up to run summer schools in 2013 will be announced shortly. further information on the p')
('School meals', 1, '\nengland’s most disadvantaged pupils are to benefit from extra cash next year when the pupil premium rises to £900 per pupil - around 50% higher than last year.\nschools receive extra cash through the premium for every child registered as eligible for free school meals (fsm) at any point in the past six years and children in care who have been looked after for six months.\nschools minister david laws said:\nit’s unacceptable that children from disadvantaged backgrounds are less likely to do well in school than')
('School meals', 2, 'lling us that the pupil premium is making a difference.\nthis extra funding will help schools provide the extra support children and young people need to reach their full potential.\nstatistics show that, in 2011, the latest available:\n35% of pupils on free school meals achieved five good gcse grades compared with 62% of other pupils.\n58% of pupils on free school meals achieved the expected level in both english and maths by the end of primary school compared with 78% of other pupils.\nthe pupil premium was in')
('School meals', 3, 'the extra support children and young people need to reach their full potential.\nstatistics show that, in 2011, the latest available:\n35% of pupils on free school meals achieved five good gcse grades compared with 62% of other pupils.\n58% of pupils on free school meals achieved the expected level in both english and maths by the end of primary school compared with 78% of other pupils.\nthe pupil premium was introduced in april 2011 and over 1.8 million disadvantaged children are benefiting from the extra cash')
('School meals', 4, 'o editors\nthe department for education has also confirmed that the per pupil level of the pupil premium for the financial year 2012 to 2013 will rise from £600 to £619. this follows a smaller-than-expected rise in the number of pupils registering for free school meals in january 2012. the allocations to schools will be revised to reflect this change in the per pupil amount.\ndetails of how secondary schools can sign up to run summer schools in 2013 will be announced shortly. further information on the pupil ')
found this here (mention #1): Sure Start at position 3543
('Sure Start', 1, 'k field’s independent report on poverty and life chances, published earlier this month, is a welcome reminder of how important early years childcare and education is to setting a child on the road to success and out of poverty.\nthat’s why we are reforming sure start services to target the most needy and are extending the offer of 15-hours of free childcare a week to all disadvantaged 2-year-olds. and through the pupil premium schools will be able to support the poorest at every stage of their education.\nrel')
found this here (mention #1): free school meals at position 4561
found this here (mention #2): free school meals at position 6850
found this here (mention #1): School meals at position 3074
found this here (mention #2): School meals at position 3138
found this here (mention #3): School meals at position 3346
found this here (mention #4): School meals at position 3623
found this here (mention #5): School meals at position 4211
found this here (mention #6): School meals at position 4566
found this here (mention #7): School meals at position 4736
found this here (mention #8): School meals at position 5154
found this here (mention #9): School meals at position 6855
found this here (mention #10): School meals at position 7196
found this here (mention #11): School meals at position 7810
('free school meals', 1, ' take up in the long-term so while a school wanting to run a really big promotion will have to invest to cover the cost, it will pay back a big return. even on a much smaller scale, we know that many schools are keen to help families who don’t qualify for free school meals but might be struggling to find money for lunches every day. we’re particularly keen to test out how these powers can help larger families with the costs of school meals and will also be producing a guide to using the new legislation for ')
('free school meals', 2, ' discount, thus helping to increase take up and thereby the financial viability of the service. * gateshead offered five days of free lunch for all reception pupils starting classes in september 2008. * as part of its main catering contract ealing provide free school meals to all of its reception children for a week. * brent ran a free meals pilot in 3 schools in 2006/07 and expanded this to 6 schools in 2007/08. in each school a year group in key stage 1 was offered a free school meal for a week. it was le')
('School meals', 1, 'eal deals for pupils starting a new school to get them into the canteen\nspecial prices for siblings regularly eating school lunches - helping families afford healthy food\ncut price meals for a different year group each day to encourage them choose healthy school meals regularly.\nchildren’s minister sarah teather said:\nschool meals beat takeaways hands down on the quality of food they serve, but up until now they have struggled to compete on price. getting children into the school canteen is vital - the bene')
('School meals', 2, 'canteen\nspecial prices for siblings regularly eating school lunches - helping families afford healthy food\ncut price meals for a different year group each day to encourage them choose healthy school meals regularly.\nchildren’s minister sarah teather said:\nschool meals beat takeaways hands down on the quality of food they serve, but up until now they have struggled to compete on price. getting children into the school canteen is vital - the benefits of healthy school meals are clear. these new powers are an ')
('School meals', 3, 'ularly.\nchildren’s minister sarah teather said:\nschool meals beat takeaways hands down on the quality of food they serve, but up until now they have struggled to compete on price. getting children into the school canteen is vital - the benefits of healthy school meals are clear. these new powers are an important step in tackling childhood obesity, and will mean schools can help hard-pressed families.\nno longer will schools be tied by complicated red tape, instead they will be able to use their initiative to')
('School meals', 4, 'r. these new powers are an important step in tackling childhood obesity, and will mean schools can help hard-pressed families.\nno longer will schools be tied by complicated red tape, instead they will be able to use their initiative to increase take up of school meals. already we’ve seen some great examples of pioneering schools keen to offer special deals - now others across the country will be able to follow suit.\njudy hargadon, chief executive of the children’s food trust and the school food trust said:\n')
('School meals', 5, 'children able to have a healthy school meal every day, and why it’s in the interests of schools to do everything they can to boost take up. keeping meals affordable is a crucial part of this, and many parents have told us that they’d be more likely to try school meals for their child if they were on offer at a discount.\nprice promotions do increase take up in the long-term so while a school wanting to run a really big promotion will have to invest to cover the cost, it will pay back a big return. even on a ')
('School meals', 6, ' up in the long-term so while a school wanting to run a really big promotion will have to invest to cover the cost, it will pay back a big return. even on a much smaller scale, we know that many schools are keen to help families who don’t qualify for free school meals but might be struggling to find money for lunches every day. we’re particularly keen to test out how these powers can help larger families with the costs of school meals and will also be producing a guide to using the new legislation for all s')
('School meals', 7, 'scale, we know that many schools are keen to help families who don’t qualify for free school meals but might be struggling to find money for lunches every day. we’re particularly keen to test out how these powers can help larger families with the costs of school meals and will also be producing a guide to using the new legislation for all schools next year.\nthe latest annual school food survey showed that, while the uptake of school lunches has increased across the board, there is a drop off of 6.5 percenta')
('School meals', 8, 'e uptake of school lunches has increased across the board, there is a drop off of 6.5 percentage points between primary and secondary school.\nresearch earlier this year by the school food trust showed that almost 6 out of 10 parents were keen to switch to school meals if they were offered price promotions.\nthe changes are part of the education act 2011, and will come into force next year. the act safeguards pupils not included in a special offer by preventing the school from charging more than the cost of p')
('School meals', 9, 'ount, thus helping to increase take up and thereby the financial viability of the service. * gateshead offered five days of free lunch for all reception pupils starting classes in september 2008. * as part of its main catering contract ealing provide free school meals to all of its reception children for a week. * brent ran a free meals pilot in 3 schools in 2006/07 and expanded this to 6 schools in 2007/08. in each school a year group in key stage 1 was offered a free school meal for a week. it was left to')
('School meals', 10, 'lot in 3 schools in 2006/07 and expanded this to 6 schools in 2007/08. in each school a year group in key stage 1 was offered a free school meal for a week. it was left to the schools to decide which year to target. this resulted in an increased uptake of school meals of 6% between february 07 and february 08.\nthe latest annual survey of school food (2010-11) showed that take up of school lunches was 44.1% in primary schools and 37.6% in secondary schools. this represented an increase over 2009-2010 of 2.7 ')
('School meals', 11, 's to about 173,000 more pupils taking school lunch in 2010-2011.\nresearch from the school food trust in september 2011, showed that 58% of parents in the survey whose children didn’t already have a school lunch said they would be willing to sign up to try school meals in september 2011, if meals were offered at a reduced price.\nthe education act 2011 (section 35) is available on the parliament website.\ndfe enquiries\ncentral newsdesk - for journalists 020 7783 8300\ngeneral enquiries - for members of the publ')
found this here (mention #1): Sure Start at position 4352
found this here (mention #2): Sure Start at position 4776
found this here (mention #3): Sure Start at position 5111
('Sure Start', 1, "cation\nkathryn broadhurst headteacher, green lane infants school, leicester. for services to education\nthomas canning headteacher, tollgate primary school, newham, london. for services to local and national education\nlaura coletti manager, violet melchett sure start children's centre, kensington, london. for services to children and families\nangela darnell headteacher, egglescliffe high school, stockton-on-tees. for services to education\nmargaret eva headteacher, bourne community college, west sussex. for s")
('Sure Start', 2, "ices to education\nmargaret eva headteacher, bourne community college, west sussex. for services to education\ntracy jackson manager, the crescent children's centre, meir, stoke on trent. for services to children and families\nlynne james manager, hartcliffe sure start children's centre, bristol. for services to children and families\ndilys jones lately headteacher, lypiatt primary school and early years centre, wiltshire. for services to education\njean jones headteacher, grace owen nursery school, sheffield. f")
('Sure Start', 3, "lys jones lately headteacher, lypiatt primary school and early years centre, wiltshire. for services to education\njean jones headteacher, grace owen nursery school, sheffield. for services to early years education\nsian rees-jones headteacher, bognor regis sure start children's centre, west sussex. for services to early years education\nroger legate principal and head of visual impairment service, linden lodge school, wandsworth, london. for services to special needs education\ncatherine myers executive headte")
found this here (mention #1): free school meals at position 3061
found this here (mention #1): School meals at position 3066
('free school meals', 1, 'st throughout their time at school.\nthe new summer schools will allow schools to pick the pupils in danger of falling back and provide them with two weeks of support and catch-up, so that they start secondary school ready to learn.\nall pupils eligible for free school meals who are making the transition between primary and secondary school in september 2012 will attract the extra funding. schools will make a judgement on which pupils need extra support in making the transition.\ndeputy prime minister, nick cl')
('School meals', 1, 'roughout their time at school.\nthe new summer schools will allow schools to pick the pupils in danger of falling back and provide them with two weeks of support and catch-up, so that they start secondary school ready to learn.\nall pupils eligible for free school meals who are making the transition between primary and secondary school in september 2012 will attract the extra funding. schools will make a judgement on which pupils need extra support in making the transition.\ndeputy prime minister, nick clegg, ')
found this here (mention #1): free school meals at position 4548
found this here (mention #1): School meals at position 4553
('free school meals', 1, 'a sense of purpose.\npeter cross, chief executive of skillforce, said:\nskillforce is delighted to be asked to expand its work with disadvantaged young people. our programmes effect positive and permanent change in their lives as evidenced by 60 per cent on free school meals going into further education compared with nine per cent nationally. the use of former military mentors enables them to serve their communities following a first career of service to their country.\ndr liam fox, secretary of state for defe')
('School meals', 1, 'se of purpose.\npeter cross, chief executive of skillforce, said:\nskillforce is delighted to be asked to expand its work with disadvantaged young people. our programmes effect positive and permanent change in their lives as evidenced by 60 per cent on free school meals going into further education compared with nine per cent nationally. the use of former military mentors enables them to serve their communities following a first career of service to their country.\ndr liam fox, secretary of state for defence s')
found this here (mention #1): free school meals at position 2434
found this here (mention #1): School meals at position 2439
('free school meals', 1, 'nment\nnick gibb has today commented on statistics showing key stage 2 attainment by pupil characteristics.\nschools minister nick gibb said:\nthese figures reveal that our education system is letting down half of all 10- and 11-year-old boys who qualify for free school meals. it is not acceptable that at the end of primary school these children are still not reaching the standard in english and maths they need to flourish at secondary school. after 7 years of primary school, children need to be fluent in thes')

In [ ]:
# 67 in the second part

In [ ]:
df_news_filtered_2025 = pd.read_csv('/content/news_filtered_2025.csv')

df_news_filtered_2025

,url,parent_url,postcodes,cc_url,content
0,https://www.gov.uk/government/news/uk-sanction...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,uk sanctions target 30 corrupt political figur...
1,https://www.gov.uk/government/news/new-funding...,www.gov.uk,['SW1P 4DF'],https://data.commoncrawl.org/crawl-data/CC-MAI...,new funding to help universities tackle antise...
2,https://govdiff.njk.onl/update/2025-10-03T07:3...,govdiff.njk.onl/update/2025-10-03T07:35:00+01:...,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,brexit guidance change explorer\nchange of htt...
3,https://govdiff.njk.onl/update/2025-10-03T09:2...,govdiff.njk.onl/update/2025-10-03T09:28:00+01:...,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,brexit guidance change explorer\nchange of htt...
4,https://www.gov.uk/government/news/nhs-staff-r...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,nhs staff receive pay rise - gov.uk\ncookies o...
...,...,...,...,...,...
1073,https://www.gov.uk/government/news/chiefs-of-s...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,chiefs of staff stand by sdsr - gov.uk\ncookie...
1074,https://www.gov.uk/government/news/ofsted-repo...,www.gov.uk,['SW1H 9EX'],https://data.commoncrawl.org/crawl-data/CC-MAI...,ofsted reports to thurrock council following f...
1075,https://www.gov.uk/government/news/opening-of-...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,opening of business applications for the new u...
1076,https://www.gov.uk/government/news/self-employ...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,self-employed invited to get ready to make the...
1077,https://www.gov.uk/government/news/new-system-...,www.gov.uk,[],https://data.commoncrawl.org/crawl-data/CC-MAI...,new system for international travel - gov.uk\n...

In [ ]:
number_results = 0
for id, row in df_news_filtered_2025.iterrows():
  result = find_keywords_present(row['content'], keywordlisttocheck)

  if len(result) > 0:
    for item in result:
      number_results += 1
      data_row = {}
      print(item)

      data_row['source'] = 'df_news_filtered_2025'
      data_row['id'] = id
      data_row['url'] = row['url']
      data_row['parent_url'] = row['parent_url']
      data_row['cc_url'] = row['cc_url']
      data_row['content_truncated'] = row['content'][0:100]
      data_row['result'] = item[0]  # keyword
      data_row['mention_number'] = item[1]  # mention count
      data_row['result_text'] = item[2]  # context text

      news_results_df = pd.concat([news_results_df, pd.DataFrame([data_row])], ignore_index=True)

print('number_results', number_results)

found this here (mention #1): free school meals at position 5094
found this here (mention #2): free school meals at position 5866
found this here (mention #1): School meals at position 5099
found this here (mention #2): School meals at position 5871
('free school meals', 1, 'ations, including government departments, the devolved administrations, local authorities, and other bodies both within and outside of government, including commercial organisations. passported benefits can be differentiated into: benefits in kind such as free school meals, free milk, fruit and vegetables, and vitamins, free prescriptions; cash benefits such as support for travel costs to hospitals or prisons; and discounts on charges or fees such as leisure discounts.\ngovernment departments and the devolve')
('free school meals', 2, ' current criteria for defining eligibility to various passported benefits will no longer exist.\nfootnote\nby passported benefits we mean those benefits to which working-age claimants of certain means-tested benefits are automatically entitled. for example, free school meals, free prescriptions, free dental treatment, etc. we will consider the range of passported benefits available to working-age claimants but the recommendations will focus on the main passported benefits. we are particularly interested in re')
('School meals', 1, 's, including government departments, the devolved administrations, local authorities, and other bodies both within and outside of government, including commercial organisations. passported benefits can be differentiated into: benefits in kind such as free school meals, free milk, fruit and vegetables, and vitamins, free prescriptions; cash benefits such as support for travel costs to hospitals or prisons; and discounts on charges or fees such as leisure discounts.\ngovernment departments and the devolved adm')
('School meals', 2, 'ent criteria for defining eligibility to various passported benefits will no longer exist.\nfootnote\nby passported benefits we mean those benefits to which working-age claimants of certain means-tested benefits are automatically entitled. for example, free school meals, free prescriptions, free dental treatment, etc. we will consider the range of passported benefits available to working-age claimants but the recommendations will focus on the main passported benefits. we are particularly interested in receivi')
found this here (mention #1): breakfast clubs at position 4294
('breakfast clubs', 1, 'y.\ninvestment to rebuild crumbling schools\nwe are committing £1.4 billion to rebuild crumbling schools.\nthe investment will ensure delivery of the existing school rebuilding programme, with 50 rebuilds a year.\nalongside funding for children’s social care, breakfast clubs and early years childcare, the investment reflects the government’s commitment to putting education back at the forefront of national life, breaking down the barriers to opportunity for all children.\nstate pension increase\nto help make sure')
found this here (mention #1): Best Start in Life at position 7198
found this here (mention #1): family hubs at position 7086
found this here (mention #1): free school meals at position 6784
found this here (mention #1): School meals at position 6789
('Best Start in Life', 1, 'ccination programme since the menb vaccine in 2015.\nmeanwhile, the department for education has recently announced plans to roll out best start family hubs in every local area, relieving pressure on parents and giving half a million more children the very best start in life.\nthe eligibility criteria for children will be set out in clinical guidance covering which age groups will get the mmrv vaccine and when, to ensure the most effective protection for children.\nas with other childhood immunisations, parent')
('family hubs', 1, 'ental care.\nthis is the first time protection against another disease has been added to the routine childhood vaccination programme since the menb vaccine in 2015.\nmeanwhile, the department for education has recently announced plans to roll out best start family hubs in every local area, relieving pressure on parents and giving half a million more children the very best start in life.\nthe eligibility criteria for children will be set out in clinical guidance covering which age groups will get the mmrv vacci')
('free school meals', 1, 'ealthy and prevent sickness from these highly contagious viruses.\nthe mmrv vaccine rollout forms part of the government’s overall aim to ensure young people thrive, as part of the 10 year health plan. this includes expanding access to vaccines, as well as free school meals, mental health support and dental care.\nthis is the first time protection against another disease has been added to the routine childhood vaccination programme since the menb vaccine in 2015.\nmeanwhile, the department for education has re')
('School meals', 1, 'y and prevent sickness from these highly contagious viruses.\nthe mmrv vaccine rollout forms part of the government’s overall aim to ensure young people thrive, as part of the 10 year health plan. this includes expanding access to vaccines, as well as free school meals, mental health support and dental care.\nthis is the first time protection against another disease has been added to the routine childhood vaccination programme since the menb vaccine in 2015.\nmeanwhile, the department for education has recentl')
found this here (mention #1): free school meals at position 4612
found this here (mention #2): free school meals at position 4865
found this here (mention #1): School meals at position 4617
found this here (mention #2): School meals at position 4870
('free school meals', 1, 'erable children i am confident we will help beat this virus.\ni am deeply grateful for the civic spirit and dedication of everyone working in education, and i will continue to provide my full support throughout this crisis.\nto support children eligible for free school meals, schools will be able to provide meals or vouchers for supermarkets or local shops.\nthe government has also confirmed that the total value of vouchers offered to each eligible child per week will exceed the rate it pays to schools for fre')
('free school meals', 2, 'or free school meals, schools will be able to provide meals or vouchers for supermarkets or local shops.\nthe government has also confirmed that the total value of vouchers offered to each eligible child per week will exceed the rate it pays to schools for free school meals, recognising that families will not be buying food in bulk and may therefore incur higher costs. the final amounts will be confirmed shortly via guidance for schools.\neffective immediately, schools will be able to order vouchers directly ')
('School meals', 1, 'e children i am confident we will help beat this virus.\ni am deeply grateful for the civic spirit and dedication of everyone working in education, and i will continue to provide my full support throughout this crisis.\nto support children eligible for free school meals, schools will be able to provide meals or vouchers for supermarkets or local shops.\nthe government has also confirmed that the total value of vouchers offered to each eligible child per week will exceed the rate it pays to schools for free sch')
('School meals', 2, 'ee school meals, schools will be able to provide meals or vouchers for supermarkets or local shops.\nthe government has also confirmed that the total value of vouchers offered to each eligible child per week will exceed the rate it pays to schools for free school meals, recognising that families will not be buying food in bulk and may therefore incur higher costs. the final amounts will be confirmed shortly via guidance for schools.\neffective immediately, schools will be able to order vouchers directly from ')
found this here (mention #1): free school meals at position 14991
found this here (mention #1): School meals at position 14996
('free school meals', 1, 'losed of individuals who are solely eligible for the standard allowance, meaning they are not receiving additional child, housing or disability universal credit payments. this means parents claiming the child element and receiving additional benefits like free school meals are not in scope of this measure and will not lose out. this is also the case for disabled claimants in receipt of the disability element of uc and receiving any additional benefits derived from their uc eligibility; investigating positiv')
('School meals', 1, ' of individuals who are solely eligible for the standard allowance, meaning they are not receiving additional child, housing or disability universal credit payments. this means parents claiming the child element and receiving additional benefits like free school meals are not in scope of this measure and will not lose out. this is also the case for disabled claimants in receipt of the disability element of uc and receiving any additional benefits derived from their uc eligibility; investigating positive cla')
number_results 15

In [ ]:
news_results_df

,source,id,url,parent_url,cc_url,content_truncated,result,mention_number,result_text
0,df_selected_urls_2024_p1,80,https://www.gov.uk/government/news/graham-alle...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,graham allen launches second report on early i...,Sure Start,1,"we are recruiting 4,200 health visitors and e..."
1,df_selected_urls_2024_p1,261,https://www.gov.uk/government/news/first-speci...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,first special and alternative provision free s...,free school meals,1,e right for local children. international evid...
2,df_selected_urls_2024_p1,261,https://www.gov.uk/government/news/first-speci...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,first special and alternative provision free s...,free school meals,2,ers and heads more freedom in the classroom he...
3,df_selected_urls_2024_p1,261,https://www.gov.uk/government/news/first-speci...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,first special and alternative provision free s...,School meals,1,ht for local children. international evidence ...
4,df_selected_urls_2024_p1,261,https://www.gov.uk/government/news/first-speci...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,first special and alternative provision free s...,School meals,2,nd heads more freedom in the classroom helps t...
...,...,...,...,...,...,...,...,...,...
159,df_news_filtered_2025,872,https://www.gov.uk/government/news/schools-col...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,"schools, colleges and early years settings to ...",free school meals,2,"or free school meals, schools will be able to ..."
160,df_news_filtered_2025,872,https://www.gov.uk/government/news/schools-col...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,"schools, colleges and early years settings to ...",School meals,1,e children i am confident we will help beat th...
161,df_news_filtered_2025,872,https://www.gov.uk/government/news/schools-col...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,"schools, colleges and early years settings to ...",School meals,2,"ee school meals, schools will be able to provi..."
162,df_news_filtered_2025,886,https://www.gov.uk/government/news/employment-...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,employment support launched for over a million...,free school meals,1,losed of individuals who are solely eligible f...
163,df_news_filtered_2025,886,https://www.gov.uk/government/news/employment-...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,employment support launched for over a million...,School meals,1,of individuals who are solely eligible for th...

In [ ]:
news_results_df

Empty DataFrame
Columns: [source, id, url, parent_url, cc_url, content_truncated, result, mention_number, result_text]
Index: []

In [ ]:
news_results_df

,source,id,url,parent_url,cc_url,content_truncated,result,result_text
0,df_news_filtered_2024_p1,80,https://www.gov.uk/government/news/graham-alle...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,graham allen launches second report on early i...,sure start,"we are recruiting 4,200 health visitors and e..."
1,df_news_filtered_2024_p1,261,https://www.gov.uk/government/news/first-speci...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,first special and alternative provision free s...,free school meals,e right for local children. international evid...
2,df_news_filtered_2024_p1,261,https://www.gov.uk/government/news/first-speci...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,first special and alternative provision free s...,school meals,ht for local children. international evidence ...
3,df_news_filtered_2024_p1,403,https://www.gov.uk/government/news/prime-minis...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,prime minister announces support for parents a...,best start in life,videos showing midwives demonstrating practic...
4,df_news_filtered_2024_p1,412,https://www.gov.uk/government/news/coasting-sc...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,coasting schools meeting - gov.uk\ncookies on ...,best start in life,"ure, and turned that school around. now he’s g..."
...,...,...,...,...,...,...,...,...
68,df_news_filtered_2025,671,https://www.gov.uk/government/news/free-chicke...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,free chickenpox vaccination offered for first ...,school meals,y and prevent sickness from these highly conta...
69,df_news_filtered_2025,872,https://www.gov.uk/government/news/schools-col...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,"schools, colleges and early years settings to ...",free school meals,erable children i am confident we will help be...
70,df_news_filtered_2025,872,https://www.gov.uk/government/news/schools-col...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,"schools, colleges and early years settings to ...",school meals,e children i am confident we will help beat th...
71,df_news_filtered_2025,886,https://www.gov.uk/government/news/employment-...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,employment support launched for over a million...,free school meals,losed of individuals who are solely eligible f...
72,df_news_filtered_2025,886,https://www.gov.uk/government/news/employment-...,www.gov.uk,https://data.commoncrawl.org/crawl-data/CC-MAI...,employment support launched for over a million...,school meals,of individuals who are solely eligible for th...

In [ ]:
# export csv results

news_results_df.to_csv('news_results_df_for_analysis.csv')